apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-ca

resources:
- ../../base
- step-ca-password.yaml

configMapGenerator:
- behavior: merge
  literals:
  - STEPCA_INIT_DNS_NAMES=step-ca.apps.nerc-ocp-infra.rc.fas.harvard.edu,step-ca.step-ca.svc.cluster.local
  name: step-ca-config

patches:
- patch: |
    - op: add
      path: /spec/host
      value: step-ca.apps.nerc-ocp-infra.rc.fas.harvard.edu
  target:
    kind: Route
    name: step-ca
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: step-ca
    spec:
      template:
        spec:
          volumes:

            - name: step-ca-password
              secret:
                secretName: step-ca-password

          initContainers:

            - name: step-ca-init
              env:
                - name: STEPCA_INIT_PASSWORD_FILE
                  value: /passwords/password
              volumeMounts:
                - name: step-ca-password
                  mountPath: /passwords

          containers:
            - name: step-ca
              image: docker.io/smallstep/step-ca:0.25.2
              command:
                - ./step-ca
                - --password-file=password
                - /home/step/config/ca.json
              ports:
                - name: http
                  containerPort: 9000
              volumeMounts:

                - name: step-ca-data
                  mountPath: /home/step
