apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-password
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: step-ca-password
  data:
  - secretKey: password
    remoteRef:
      key: nerc/nerc-ocp-infra/step-ca/step-ca-password
      property: password
