apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

configMapGenerator:
  - name: step-ca-config
    behavior: merge
    literals:
      - STEPCA_INIT_DNS_NAMES=step-ca.apps.nerc-ocp-test.rc.fas.harvard.edu,step-ca.step-ca.svc.cluster.local

patches:
  - target:
      kind: Route
      name: step-ca
    patch: |
      - op: add
        path: /spec/host
        value: step-ca.apps.nerc-ocp-test.rc.fas.harvard.edu
