apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-ca
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      volumes:

        - name: step-ca-data
          persistentVolumeClaim:
            claimName: step-ca-data

        - name: step-ca-config
          configmMap:
            name: step-ca-config

      initContainers:

        - name: step-ca-init
          image: docker.io/smallstep/step-ca:0.25.2
          envFrom:
            - configMapRef:
                name: step-ca-config
          command:
            - sh
            - -c
            - |
              set -eu

              if ! [ -f /home/step/config/ca.json ]; then

                echo "initializing step-ca"

                if [ -z "$STEPCA_INIT_PASSWORD_FILE" ]; then
                  tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 30 > password
                  echo "Your password is: $(cat password)"
                else
                  cp "$STEPCA_INIT_PASSWORD_FILE" password
                fi

                step ca init \
                  --name="$STEPCA_INIT_NAME" \
                  --dns="$STEPCA_INIT_DNS_NAMES" \
                  --address=":9000" \
                  --provisioner="$STEPCA_INIT_PROVISIONER_NAME" \
                  --password-file=password \
                  --provisioner-password-file=password \
                  --remote-management \
                  --admin-subject="$STEPCA_INIT_ADMIN_SUBJECT"

              else

                echo "step-ca has already been initialized"

              fi

              # This is because of a weird EPERM issue trying to run
              # the binary from /usr/local/bin.
              cp /usr/local/bin/step-ca ./step-ca
          volumeMounts:

            - name: step-ca-data
              mountPath: /home/step

      containers:
        - name: step-ca
          image: docker.io/smallstep/step-ca:0.25.2
          command:
            - ./step-ca
            - --password-file=password
            - /home/step/config/ca.json
          ports:
            - name: http
              containerPort: 9000
          volumeMounts:

            - name: step-ca-data
              mountPath: /home/step
